<?php 
$previewUrl =  $block->getPreviewUrl(); 
$createUrl =  $block->getCreateUrl(); 

$id = $block->getCurrentSlider();
?>
<script>
    
    require([
        'jquery',
        'ibnabsliders'
    ], function ($,ibnabsliders) {
       
         ibnabSlider.initialize();
         $("#sliders_preview").on( "click", function() {
           ibnabSlider.open('<?php echo $previewUrl; ?>','<?php echo $id; ?>');
         });
         /*
         $("#create_banner").on( "click", function() {
           ibnabSlider.openCreate('<?php echo $createUrl; ?>','<?php echo $id; ?>');
         });
         */
        
    });
</script>

<div id="preview-modal">
            <div class="admin__data-grid-outer-wrap" data-bind="scope: 'OnclickShowPreview'">
                <!-- ko template: getTemplate() --><!-- /ko -->

            </div>
</div>
<div id="create-modal">
            <div class="admin__data-grid-outer-wrap" data-bind="scope: 'OnclickShowCreate'">
                <!-- ko template: getTemplate() --><!-- /ko -->

            </div>
</div>