<?php
$model = $block->getSlider();
$dataModel = $model->getData();
$id = uniqid();
$banners = $block->getBanners();
$baseMediaUrl = $block->getBaseMediaUrl();
$prams = $model->getAllParamsOwl();
?>
<?php if($model->getType() == $model::SLIDER_TYPE_BANNER): ?>
<div id="owl-slider<?php echo $id ?>" class="owl-carousel">
    <?php foreach ($banners as $banner): ?>
        <div class="item"><img src="<?php echo $baseMediaUrl . "/" . $banner->getImage() ?>" alt="The Last of us"></div>
        <?php endforeach; ?>
</div>

<script>

    require([
        'jquery',
        'ibnabowlsliders'
    ], function ($, ibnabowlsliders) {
        $(document).ready(function () {
            $("#owl-slider<?php echo $id ?>").owlCarousel({
                <?php echo $prams ?>
            });
        });
    });
</script>
<?php else: ?>
<?php 
?>
<?php $_items = $block->getSliderProductsCollection($model->getType()) ?>
<?php if(count($_items)==0) : ?>
<?php return  ?>
<?php endif ?>

<?php $_helper = $this->helper('Magento\Catalog\Helper\Output') ?>
<?php $sliderId = $model->getId() ?>

<?php $image = 'category_page_grid';
$_helperGallery = $this->helper('Ibnab\Common\Helper\Data'); ?>
<?php $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW ?>
<?php $viewMode = 'grid' ?>
<?php $class = $model->getType() ?>
<?php $type = "" ?>
<?php $showWishlist =  isset($dataModel['displayWishlist']) ? $dataModel['displayWishlist'] : 1 ?>
<?php $showCompare = isset($dataModel['displayCompare']) ? $dataModel['displayCompare'] : 1  ?>
<?php $showCart = isset($dataModel['displayCart']) ? $dataModel['displayCart'] : 1 ?>
<?php $showTitle = isset($dataModel['displayTitle']) ? $dataModel['displayTitle'] : 1 ?>
<?php $showPrice = isset($dataModel['displayPrice']) ? $dataModel['displayPrice'] : 1 ?>
<div class="block block-product-slider slider-list <?php /* @escapeNotVerified */ echo $class; ?>" <?php echo $model->getRtl() ? 'dir="rtl" ' : "" ?> >
    <?php if($showTitle): ?>
        <div class="block-title title">
            <strong id="block-<?php /* @escapeNotVerified */ echo $class?>-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo $model->getTitle() ?></strong>
        </div>
    <?php endif ?>
    <div class="block-content content" aria-labelledby="block-<?php /* @escapeNotVerified */ echo $class?>-heading">
        <?php if(!empty($_items)): ?>
            <div class="products wrapper grid products-grid products-<?php /* @escapeNotVerified */ echo $type; ?>">
            <ol class="products list items product-slider<?php echo $sliderId ?>">
                    <?php $iterator = 1; ?>
                <div id="owl-slider<?php echo $id ?>" class="owl-carousel">
                    <?php foreach ($_items as $_item): ?>
                    <div class="item">
                    <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                     
                     <div class="product-item-info<?php echo $model->getGrid() ? '' : '-'.$class ?>">
                        <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
                            <?php //    echo $block->getImage($_item, $image)->toHtml(); ?>
                            <ul class="cd-item-wrapper">
                                <?php
                                $_helperGallery->addGallery($_item);
                                $images = $_helperGallery->getGalleryImages($_item);
                                if ($images instanceof \Magento\Framework\Data\Collection) {
                                    $is = 0;
                                    foreach ($images as $image) {
                                        $imageItem = $image->getData();
                                        if (isset($imageItem['media_type']) && $imageItem['media_type'] == 'image'):
                                            ?>
                                                <img  onload="this.width/=2;this.onload=null;" src="<?php echo isset($imageItem['small_image_url']) ? $imageItem['small_image_url'] : null; ?>" alt="Preview image">
                                            </li>
                                            <?php
                                            $is = 1;
                                            break;
                                        endif;
                                    }

                                    }
                                ?>
                            </ul>
                        </a>
                        <div class="product details product-item-details">
                        <strong class="product name product-item-name"><a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
                            <?php echo $block->escapeHtml($_item->getName()) ?></a>
                        </strong>
                        <?php if($showPrice): ?>
                            <?php /* @escapeNotVerified */ echo $block->getProductPrice($_item); ?>
                        <?php endif ?>
                            <?php if ($templateType): ?>
                                <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                            <?php endif; ?>

                            <?php if ($showWishlist || $showCompare || $showCart): ?>
                                <div class="product actions product-item-actions">
                                    <?php if ($showCart): ?>
                                        <div class="actions-primary">
                                            <?php if ($_item->isSaleable()): ?>
                                                <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                    <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                    </button>
                                                <?php else: ?>
                                                    <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                    $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                    ?>
                                                    <button class="action tocart primary"
                                                            data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                            type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                    </button>
                                                <?php endif; ?>
                                            <?php else: ?>
                                                <?php if ($_item->getIsSalable()): ?>
                                                    <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>

                                    <?php if ($showWishlist || $showCompare): ?>
                                        <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'  class="action towishlist" data-action="add-to-wishlist" title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                                </a>
                                            <?php endif; ?>
                                            <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                <?php
                                                $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                                ?>
                                                <a href="#" class="action tocompare"
                                                   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item);?>'
                                                   data-role="add-to-links"
                                                   title="<?php /* @escapeNotVerified */ echo __('Add to Compare'); ?>">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                                </a>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                    
                    <?php echo($iterator == count($_items)+1) ? '</li>' : '' ?>
                    </div>
                    <?php endforeach ?>
                    </div>
            </ol>
        </div>
        <?php endif ?>
    </div>
</div>
<?php if(!count($_items)==0):?>
<script>

    require([
        'jquery',
        'ibnabowlsliders'
    ], function ($, ibnabowlsliders) {
        $(document).ready(function () {
            $("#owl-slider<?php echo $id ?>").owlCarousel({
                <?php echo $prams ?>
            });
        });
    });
</script>
<?php endif; ?>
<?php endif; ?>